# Generated by Django 4.2.4 on 2023-09-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='last_name',
        ),
    ]
