# Generated by Django 4.2.4 on 2023-09-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0003_userinformation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
