# Generated by Django 4.2.4 on 2023-09-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0004_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
