# Generated by Django 4.2.4 on 2023-09-06 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slice', '0006_course_usercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=50)),
                ('gram', models.IntegerField()),
                ('adult', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=50)),
                ('gram', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='package',
            new_name='course',
        ),
        migrations.CreateModel(
            name='User_Coffee_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_delivery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='slice.coffee_delivery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Academy_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='slice.academy_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
