# Generated by Django 4.2.4 on 2023-09-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0007_academy_product_coffee_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_product',
            name='image',
            field=models.ImageField(default=True, upload_to='academy_product_images/'),
        ),
        migrations.AddField(
            model_name='coffee_delivery',
            name='image',
            field=models.ImageField(default=True, upload_to='coffee_delivery_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default=True, upload_to='course_images/'),
        ),
    ]
