# Generated by Django 4.2.4 on 2023-09-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0012_rename_products_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
