# Generated by Django 4.2.4 on 2023-09-09 02:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slice', '0013_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='MyCart',
        ),
    ]
