# Generated by Django 4.2.4 on 2023-09-09 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0017_academy_product_discount_price_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slice.course'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='userinformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slice.userinformation'),
        ),
    ]
