# Generated by Django 4.2.4 on 2023-09-11 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0019_remove_cartitem_academy_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_type',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='academy_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slice.academy_product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='coffee_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slice.coffee_delivery'),
        ),
    ]
