# Generated by Django 4.2.4 on 2023-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0020_remove_cartitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='first_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='last_name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
