# Generated by Django 4.2.4 on 2023-09-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0021_userinformation_first_name_userinformation_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, null=True),
        ),
    ]
