# Generated by Django 4.2.4 on 2023-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0025_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coffee_delivery',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
