# Generated by Django 4.2.4 on 2023-09-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0026_alter_academy_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='academy_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slice.academy_product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='coffee_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slice.coffee_delivery'),
        ),
    ]
