# Generated by Django 4.2.4 on 2023-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0027_notification_academy_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
