# Generated by Django 4.2.4 on 2023-09-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0028_rename_first_name_userinformation_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slice.userinformation'),
        ),
    ]
