# Generated by Django 4.2.4 on 2023-09-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0034_paymentconfirmation_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='reference_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
