# Generated by Django 4.2.4 on 2023-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0035_alter_paymentconfirmation_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='order_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
