# Generated by Django 4.2.4 on 2023-09-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0036_alter_userinformation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('chocolate', 'Chocolate'), ('cream', 'Cream'), ('pancake', 'Pancake')], max_length=20)),
            ],
        ),
    ]
